version: '3.8'

services:

  second-eye-server:
    build:
      context: ./server
      dockerfile: Dockerfile.i1
    container_name: second-eye-server
    volumes:
      - ./server:/usr/src/app
    networks:
      - second-eye-network

  second-eye-client:
    build:
      context: ./client
      dockerfile: Dockerfile.i1
      args:
        - REACT_APP_SECOND_EYE_API_URL=http://localhost:8000/graphql/
    container_name: second-eye-client
    depends_on:
      - second-eye-server
    ports:
      - 3000:80
    stdin_open: true
    environment:
      - NGINX_SECOND_EYE_SERVER=http://second-eye-server:8000
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    networks:
      - second-eye-network

networks:
  second-eye-network: