from second_eye_api.models.entities import DedicatedTeamPlanningPeriodTimeSpentPercentWithValueAndWithoutValueByDate
from second_eye_api.migrate_from_external_db.load.utils import load_dataframe_to_db

class DedicatedTeamPlanningPeriodTimeSpentPercentWithValueAndWithoutValueByDateLoader:
    def __init__(self, dedicated_team_planning_period_time_spent_percent_with_value_and_without_value_by_date, output_database):
        self.dedicated_team_planning_period_time_spent_percent_with_value_and_without_value_by_date = dedicated_team_planning_period_time_spent_percent_with_value_and_without_value_by_date
        self.output_database = output_database

    def load(self):
        dedicated_team_planning_period_time_spent_percent_with_value_and_without_value_by_date = self.dedicated_team_planning_period_time_spent_percent_with_value_and_without_value_by_date
        output_database = self.output_database

        load_dataframe_to_db(dataframe=dedicated_team_planning_period_time_spent_percent_with_value_and_without_value_by_date, model=DedicatedTeamPlanningPeriodTimeSpentPercentWithValueAndWithoutValueByDate, output_database=output_database)