# Generated by Django 3.2.5 on 2021-08-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_eye_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatedteampositionability',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dedicatedteampositionability',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_team_position_abilities', to='second_eye_api.skill'),
        ),
        migrations.AlterField(
            model_name='dedicatedteampositionability',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_team_position_abilities', to='second_eye_api.system'),
        ),
        migrations.CreateModel(
            name='ProjectTeamPositionAbility',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_team_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='second_eye_api.projectteamposition')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_team_position_abilities', to='second_eye_api.skill')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_team_position_abilities', to='second_eye_api.system')),
            ],
        ),
    ]
