# Generated by Django 3.2.5 on 2021-07-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_eye_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dedicatedteam',
            name='url',
        ),
    ]
