# Generated by Django 3.2.5 on 2021-07-27 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_eye_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FunctionComponentType',
            new_name='FunctionComponentKind',
        ),
        migrations.AlterField(
            model_name='task',
            name='system_change_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='second_eye_api.systemchangerequest'),
        ),
    ]
