# Generated by Django 3.2.5 on 2021-07-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_eye_api', '0002_remove_dedicatedteam_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='url',
        ),
    ]
