# Generated by Django 3.2.5 on 2021-07-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_eye_api', '0002_auto_20210727_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functioncomponent',
            old_name='function_component_type',
            new_name='function_component_kind',
        ),
    ]
