# Generated by Django 3.2.5 on 2021-07-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_eye_api', '0003_remove_projectteam_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
